from _typeshed import Incomplete
from collections.abc import Generator
from itemadapter import ItemAdapter as ItemAdapter, is_item as is_item
from typing import Self

class ScrapyPokedexSpiderMiddleware:
    @classmethod
    def from_crawler(cls, crawler) -> Self: ...
    def process_spider_input(self, response, spider) -> None: ...
    def process_spider_output(self, response, result, spider) -> Generator[Incomplete]: ...
    def process_spider_exception(self, response, exception, spider) -> None: ...
    def process_start_requests(self, start_requests, spider) -> Generator[Incomplete]: ...
    def spider_opened(self, spider) -> None: ...

class ScrapyPokedexDownloaderMiddleware:
    @classmethod
    def from_crawler(cls, crawler): ...
    def process_request(self, request, spider) -> None: ...
    def process_response(self, request, response, spider): ...
    def process_exception(self, request, exception, spider) -> None: ...
    def spider_opened(self, spider) -> None: ...
