from _typeshed import Incomplete

SPIDER: str
ENABLE_DEBUG: bool
MAX_ROWS: int | None
DEFAULT_OUTPUT: bool
BOT_NAME: str
SPIDER_MODULES: list[str]
NEWSPIDER_MODULE: str
ROBOTSTXT_OBEY: bool
CONCURRENT_REQUESTS: int
DOWNLOAD_DELAY: int
CONCURRENT_REQUESTS_PER_DOMAIN: int
COOKIES_ENABLED: bool
TELNETCONSOLE_ENABLED: bool
SPIDER_MIDDLEWARES: dict[str, int | None]
RANDOM_UA_PER_PROXY: bool
RANDOM_UA_TYPE: str
RANDOM_UA_SAME_OS_FAMILY: bool
PROXY_LIST: str
PROXY_MODE: int
RETRY_TIMES: int
RETRY_HTTP_CODES: Incomplete
DOWNLOADER_MIDDLEWARES: dict[str, int | None]
EXTENSIONS: dict[str, int | None]
ITEM_PIPELINES: dict[str, int | None]
AUTOTHROTTLE_ENABLED: bool
AUTOTHROTTLE_START_DELAY: int
AUTOTHROTTLE_MAX_DELAY: int
AUTOTHROTTLE_TARGET_CONCURRENCY: float
AUTOTHROTTLE_DEBUG: bool
HTTPCACHE_ENABLED: bool
HTTPCACHE_EXPIRATION_SECS: Incomplete
HTTPCACHE_DIR: str
HTTPCACHE_IGNORE_HTTP_CODES: list[str | int]
HTTPCACHE_STORAGE: str
LOG_ENABLED: bool
TWISTED_REACTOR: str
