from _typeshed import Incomplete

BOT_NAME: str
SPIDER_MODULES: Incomplete
NEWSPIDER_MODULE: str
ROBOTSTXT_OBEY: bool
CONCURRENT_REQUESTS: int
COOKIES_ENABLED: bool
TELNETCONSOLE_ENABLED: bool
AUTOTHROTTLE_ENABLED: bool
AUTOTHROTTLE_START_DELAY: int
AUTOTHROTTLE_MAX_DELAY: int
AUTOTHROTTLE_TARGET_CONCURRENCY: float
AUTOTHROTTLE_DEBUG: bool
HTTPCACHE_ENABLED: bool
HTTPCACHE_EXPIRATION_SECS: int
HTTPCACHE_DIR: str
HTTPCACHE_IGNORE_HTTP_CODES: list[str | int]
HTTPCACHE_STORAGE: str
REQUEST_FINGERPRINTER_IMPLEMENTATION: str
TWISTED_REACTOR: str
FEED_EXPORT_ENCODING: str
