repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trailing Whitespace
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: check-yaml
        name: Check YAML
      - id: check-added-large-files
        name: Check Large Files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        name: Ruff Linter
        types_or: [python, pyi, jupyter]
        args: [--fix]

      - id: ruff-format
        name: Ruff Formatter
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18
    hooks:
      - id: mdformat
        name: Markdown Formatter
        additional_dependencies:
          - mdformat-ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Mypy Type Checker
        args: [--ignore-missing-imports]
