from ..util.interceptor import InterceptHandler as InterceptHandler
from scrapy_pokedex.scripts.constants import DATA_DIR as DATA_DIR, DATA_OUTPUT_DIR as DATA_OUTPUT_DIR, LOG_DIR as LOG_DIR

def run() -> None: ...
def types() -> None: ...
